##
# Plugins
require:
  - standard

##
# Defaults: standard-rb
inherit_gem:
  standard: config/base.yml

AllCops:
  TargetRubyVersion: 3.1
  Include:
    - 'lib/**/*.rb'
    - 'test/**/*.rb'

Style/MultilineIfModifier:
  Exclude:
    - 'lib/test-cmd.rb'
